name: Deploy website

on: [push]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build website
        run: |
          bun install
          bun run build
      
      - name: Deploy website
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _BUILD