name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: lts/*
      
      - name: Build
        run: |
          npm install
          npx pug -o www src/index.pug

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: www
